homepage:
    path: /
    defaults:  { _controller: BuilderPageBundle:Builder\BuildPage:buildPage, slug: "accueil" }
    # defaults: 
    #     _controller: FrameworkBundle:Redirect:urlRedirect
    #     path: /accueil
    #     permanent: true

site_loginpage:
    path:     /login/page
    defaults: { _controller: BuilderPageBundle:Builder\BuildPage:buildPage, slug: "login" }

site_login:
    path:     /login
    # defaults: { _controller: BuilderPageBundle:Builder\BuildPage:buildPage, slug: "login" }
    # RENVOI vers la route de login de fosuserbundle

# site_popup:
#     path:     /popup/{slug}
#     defaults: { _controller: BuilderPageBundle:Builder\BuildContent:buildPageContent }


# FOR DEBUG PAGE:
# builder_buildpagedetails:
#     path:      /details/{slug}
#     defaults:
#         _controller: BuilderPageBundle:Builder\BuildPage:buildPageDetails

front_sitemap:
    path:      /sitemap.{_format}
    defaults: { _controller: BuilderPageBundle:SiteMap\SiteMap:siteMap }
    requirements: 
        _format: "xml"

builder_buildpageid:
    path:      /{slug}/{id}
    defaults:
        _controller: BuilderPageBundle:Builder\BuildPage:buildPage


#MAIN ROUTE ALL MATCH:
builder_buildpage_base:
    path:      /{slug}
    defaults:  { _controller: BuilderPageBundle:Builder\BuildPage:buildPage, slug: "accueil" }

builder_buildpage:
    path:      /{slug}/
    defaults:  { _controller: BuilderPageBundle:Builder\BuildPage:buildPage, slug: "accueil" }
