homepage:
    path: /
    defaults: 
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /home
        permanent: true

# portail_basetemplate:
#     path: /basetemplate
#     defaults: { _controller: MNHNPortailBundle:Template:basetemplate}

# builder_buildpage_old:
#     path:      /page/{slug}
#     defaults:  { _controller: MNHNPortailBundle:Template:buildPage, slug: "home" }
#     requirements:
#         slug: .+




#V2: intégration directe du template_repo défini dans parameters.yml
# builder_buildpage2:
#     path:      /{slug}
#     defaults:  { _controller: MNHNPortailBundle:Template:buildPage, slug: "home" }

mnhn_loginpage:
    path:     /login/page
    defaults: { _controller: BuilderPageBundle:Builder\BuildPage:buildPage, slug: "login" }

mnhn_login:
    path:     /login
    # defaults: { _controller: BuilderPageBundle:Builder\BuildPage:buildPage, slug: "login" }
    # RENVOI vers la route de login de fosuserbundle

mnhn_popup:
    path:     /popup/{slug}
    defaults: { _controller: BuilderPageBundle:Builder\BuildContent:buildPageContent }


builder_buildpagedetails:
    path:      /details/{slug}
    defaults:
        _controller: BuilderPageBundle:Builder\BuildPage:buildPageDetails


builder_buildpageid:
    path:      /{slug}/{id}
    defaults:
        _controller: BuilderPageBundle:Builder\BuildPage:buildPage
    requirements:
        id:  \d+

builder_buildpagetab:
    path:      /{slug}/{tab}
    defaults:
        _controller: BuilderPageBundle:Builder\BuildPage:buildPage


#MAIN ROUTE ALL MATCH:
builder_buildpage:
    path:      /{slug}/
    defaults:  { _controller: BuilderPageBundle:Builder\BuildPage:buildPage, slug: "home" }
